version: "3"

services:
  filebrowser:
    image: reg.barbaralabs.com/bbr_test/filebrowser:latest
    ports:
      - 8080:8080
    volumes:
      - ./filebrowser:/shared

  python_test:
    build: .